//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC2Info.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ap-northeast-1</string>
  <string>ap-northeast-2</string>
  <string>ap-southeast-1</string>
  <string>ap-southeast-2</string>
  <string>ap-south-1</string>
  <string>ca-central-1</string>
  <string>eu-central-1</string>
  <string>eu-west-1</string>
  <string>eu-west-2</string>
  <string>sa-east-1</string>
  <string>us-east-1</string>
  <string>us-east-2</string>
  <string>us-west-1</string>
  <string>us-west-2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AWSRegion {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AWSRegion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eu-west-1")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string AWSDefaultRegion {
            get {
                return ((string)(this["AWSDefaultRegion"]));
            }
            set {
                this["AWSDefaultRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>default|arn:aws:iam::049793823615:mfa/rbowden.kcom.adm</string>\r\n</ArrayOf" +
            "String>")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::System.Collections.Specialized.StringCollection MFADevices {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MFADevices"]));
            }
            set {
                this["MFADevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>CA_KCOM_ADM @ easyJet Non-Prod|arn:aws:iam::640467343547:role/CA_KCOM_ADM</string>
</ArrayOfString>")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::System.Collections.Specialized.StringCollection Roles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Roles"]));
            }
            set {
                this["Roles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name,InstanceId,PrivateIpAddress,PublicIpAddress,VpcId,SubnetId,KeyName,SecurityG" +
            "roups")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string EC2SavedProperties {
            get {
                return ((string)(this["EC2SavedProperties"]));
            }
            set {
                this["EC2SavedProperties"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public string Version {
            get {
                return ((string)(this["Version"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::System.Collections.Specialized.StringCollection VersionsToIgnore {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VersionsToIgnore"]));
            }
            set {
                this["VersionsToIgnore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public global::System.DateTime VersionsRemindDate {
            get {
                return ((global::System.DateTime)(this["VersionsRemindDate"]));
            }
            set {
                this["VersionsRemindDate"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/rickbowden/EC2Info/releases/latest")]
        public string UpdateUrl {
            get {
                return ((string)(this["UpdateUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Architecture</string>
  <string>EbsOptimized</string>
  <string>EnaSupport</string>
  <string>Hypervisor</string>
  <string>IamInstanceProfile</string>
  <string>InstanceId</string>
  <string>InstanceType</string>
  <string>KernelId</string>
  <string>KeyName</string>
  <string>LaunchTime</string>
  <string>Monitoring</string>
  <string>Name</string>
  <string>Platform</string>
  <string>PrivateDnsName</string>
  <string>PrivateIpAddress</string>
  <string>PublicDnsName</string>
  <string>PublicIpAddress</string>
  <string>RootDeviceName</string>
  <string>RootDeviceType</string>
  <string>SecurityGroups</string>
  <string>SubnetId</string>
  <string>State</string>
  <string>ImageId</string>
  <string>VpcId</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EC2Properties {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EC2Properties"]));
            }
        }
    }
}
